### ISSUE TITLE
download daymet tiles failure?

### ISSUE THREAD

**Issue by tmieno2** [khufkens/daymetr#41]
When I run this, 

```r
download_daymet_tiles(
  location = c(36.61,-83.37,35.57,-81.29),
  start = 1980,
  end = 1980,
  param = "tmin"
)
```

I get this

```
Downloading DAYMET data for tile: 11209; year: 1980; product: tmin
  |==================================================| 100%

Downloading DAYMET data for tile: 11210; year: 1980; product: tmin
  |==================================================| 100%

Downloading DAYMET data for tile: 11389; year: 1980; product: tmin
  |==================================================| 100%

Downloading DAYMET data for tile: 11390; year: 1980; product: tmin
  |==================================================| 100%
```

But, only the downloaded file for the first tile (11209) seems to have actual data in it. This behavior is consistently observed for other geographic extents I tried. Am I missing something?

**Comment by khufkens** [comment]
Install the dev release from github (see NEWS item below).

https://bluegreen-labs.github.io/daymetr/news/index.html

Few people download tiles and I'm overcommitted so I haven't pushed the new releases to CRAN.

**Comment by tmieno2** [comment]
Thanks!

Haha. Yes, indeed. I am just using the function for an illustration purpose for my class but not for practical purposes.

**Comment by khufkens** [comment]
Hope the package is useful in class!

**Comment by tmieno2** [comment]
Oh, it is. The package has been  plenty useful for my research as well. Thanks for the package!

**Comment by khufkens** [comment]
Good to hear, happy hacking, let me know if you run into issues and don't forget to cite it! :-)

**Comment by tmieno2** [comment]
Yup.
